paths: # Absolute paths will be constructed at runtime
  root: /home/zeio/snip/resources/models/bert
  config: config.json
  vocabulary: vocab.txt
  checkpoint: model.ckpt-700000
size: 144
is-lower-cased: False
max-sequence-length: 256
layer-indices:
  - -6
  - -5
tpu:
  enabled: False
  master: null
  n-cores: 8
batch-size: 8
should-use-one-hot-embeddings: False
separators:
  context-tokens: ' '
alignment-strategy: mean
